var express=require('express');
var app = express();
var PORT= process.env.PORT || 5000;

var URLs={
    original:'http://www.google.com',
    short:'http://localhost:5000/c001'
}
app.use(express.static(__dirname + '/public'));
app.get('/', function(req,res){
    res.sendFile(__dirname + '/views/index.html');
    });



app.get('/short/*', function(req, res){
var long= (req.params[0]);
var expression= /^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$/;
var validURL = new RegExp(expression);
var host= req.headers.host;

if (long==URLs.short){
    res.redirect(URLs.original);

}

if (long.match(validURL)){
    URLs.original=long;
    URLs.short='http://'+host+'/'+ shortener(long);
   res.send('<code>'+JSON.stringify(URLs)) +'<code>';
  // res.redirect(long);
}else{

    res.send('false');
  

}
});


app.get('/:sURL', function (req,res){
var sURL=req.params.sURL;
var expression= /^c0*(?:[1-9][0-9]?|100)/;
var vparam = new RegExp(expression);
var host= req.headers.host;

if(sURL.match(vparam)){
    if (URLs.short==='http://'+host+'/'+sURL){
        res.redirect(URLs.original);
    }else{
        res.send("Sorry, that URL is not in my data base!")
    }

}else{
    res.send("Sorry, that parameter isn't generated by me!!!");
}
});


function shortener (url) {
var randomN= Math.floor((Math.random()*1000)+1);
return 'c'+ randomN;
  }
    


app.listen(PORT, function(){
console.log('Connected on port:'+ PORT)
});



