var express=require('express');
var app = express();
var PORT= process.env.PORT || 5000;

var URLs={
    original:'http://www.google.com',
    short:'https://url-shor-t.herokuapp.com/c001'
}
//app.use(express.static(__dirname + '/public'));
app.get('/', function(req,res){
    var host= req.headers.host;


    res.send('<h1 class="header">FreeCodeCamp API Basejump: URL Shortener Microservice</h1>'+
'<blockquote> <p>User stories:</p><ul><li>I can pass a URL as a parameter and I will receive a shortened URL in the JSON response.</li>'+
            '<li>When I visit that shortened URL, it will redirect me to my original link. </li>   </ul> </blockquote>'+
     
    '<h3>Example creation usage:</h3> <code>https://url-shor-t.herokuapp.com/short/https://www.google.com</code><br/>'+
    '<code>'+host+'short/http://foo.com</code><h3>Example creation output</h3><code>{'+
        '"original_url":"' + URLs.original +'", "short_url":"'+ URLs.short +'"'+
     ' }</code><h3>Usage:</h3><code>'+ URLs.short+ '</code><h3>Will redirect to:</h3><code>https://www.google.com/</code></div>'
    );
    });



app.get('/short/*', function(req, res){
var long= (req.params[0]);
var expression= /^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$/;
var validURL = new RegExp(expression);
var host= req.headers.host;

if (long==URLs.short){
    res.redirect(URLs.original);

}

if (long.match(validURL)){
    URLs.original=long;
    URLs.short='http://'+host+'/'+ shortener(long);
   res.send('<code>'+JSON.stringify(URLs)) +'<code>';
  // res.redirect(long);
}else{

    res.send('false');
  

}
});


app.get('/:sURL', function (req,res){
var sURL=req.params.sURL;
var expression= /^c0*(?:[1-9][0-9]?|100)/;
var vparam = new RegExp(expression);
var host= req.headers.host;

if(sURL.match(vparam)){
    if (URLs.short==='http://'+host+'/'+sURL){
        res.redirect(URLs.original);
    }else{
        res.send("Sorry, that URL is not in my data base!")
    }

}else{
    res.send("Sorry, that parameter isn't generated by me!!!");
}
});


function shortener (url) {
var randomN= Math.floor((Math.random()*1000)+1);
return 'c'+ randomN;
  }
    


app.listen(PORT, function(){
console.log('Connected on port:'+ PORT)
});



